version: "3.7"

services:
  nft-ticket-maria-db:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:
